version: '3.3'

services:
    redis:
        image: redis
    db:
      image: postgres:13.2-alpine
      restart: unless-stopped
      environment:
        POSTGRES_PASSWORD: example
      container_name: db
      volumes:
        - ./database:/var/lib/postgresql/data
    be:
      image: hilgardvr/36_be
      environment:
        - REDIS_HOST=redis
        - POSTGRES_HOST=db
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=example
        - POSTGRES_DATABASE=postgres
      depends_on: 
        - db
    fe:
      image: hilgardvr/36_fe
      depends_on:
        - be
    nginx:
      image: nginx:stable-alpine
      ports:
          - 80:80
      volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf
