version: '3.3'

services:
    redis:
        image: redis
    db:
      image: postgres:13.2-alpine
      restart: unless-stopped
      environment:
        POSTGRES_PASSWORD: example
      container_name: db
      volumes:
        - ./database:/var/lib/postgresql/data
    be:
      image: hilgardvr/example-backend
      ports:
        - 9000:9000
      environment:
        - REDIS_HOST=redis
        - POSTGRES_HOST=db
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=example
        - POSTGRES_DATABASE=postgres
      depends_on: 
        - db
    fe:
      image: hilgardvr/example-frontend
      ports:
        - 5000:5000
      depends_on:
        - be
