version: '3.3'

services:
    be:
        image: hilgardvr/example-backend
        ports:
            - 9000:9000
    fe:
        image: hilgardvr/example-frontend
        ports:
            - 5000:5000
