version: '3.3'

services:
  be:
    image: hilgardvr/27_be
    ports:
      - 5000:5000
    depends_on:
      - training
    volumes:
      - model:/src/model
  fe:
    image: hilgardvr/27_fe
    ports:
      - 3000:3000
    depends_on:
      - be
  training:
    image: hilgardvr/27_training
    volumes:
      - data:/src/data
      - model:/src/model 


volumes:
  data:
  model:
