version: '3.3'

services:
  be:
    build: ./ml-kurkkumopo-backend
    ports:
      - 5000:5000
    depends_on:
      - training
    volumes:
      - data:/src/data
      - model:/src/model
  fe:
    build: ./ml-kurkkumopo-frontend
    ports:
      - 3000:3000
    depends_on:
      - be
  training:
    build: ./ml-kurkkumopo-frontend
    volumes:
      - data:/data
      - model:/model 


volumes:
  data:
  model:
