version: '3.8'

services:
    redis:
        image: redis
    be:
        build: ./be/
        ports:
            - 9000:9000
        environment:
            - REDIS_HOST=redis
    fe:
        build: ./fe/
        ports:
            - 5000:5000
