version: '3.3'

services:
    redis:
        image: redis
    be:
        image: hilgardvr/example-backend
        ports:
            - 9000:9000
        environment:
            - REDIS_HOST=redis
    fe:
        image: hilgardvr/example-frontend
        ports:
            - 5000:5000
