FROM openjdk:8 AS builder

WORKDIR /usr/src/app

COPY . .

RUN ./mvnw package


FROM fabric8/java-alpine-openjdk8-jre:1.8

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/target ./target

USER guest

CMD ["java", "-jar", "./target/docker-example-1.1.3.jar"]
